FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        dnsutils \
        less \
        net-tools \
    && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash main
USER main
WORKDIR /home/main

RUN mkdir -p secrets
VOLUME secrets/tls

RUN mkdir -p configs
VOLUME configs/envoy

COPY bin/envoy envoy

ENTRYPOINT ["./envoy", "-c", "configs/envoy/config.yaml"]
