FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        dnsutils \
        less \
        net-tools \
    && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash main
USER main
WORKDIR /home/main

COPY bin/inner inner

ENTRYPOINT ["./inner"]
